version: '3.9'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: sh -c "npm run start:dev" # run server in dev mode.
    restart: 'always'
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    depends_on: mongo

  # Command line for install, check
  node-cli:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    restart: 'no'
    volumes:
      - ./app:/app
    environment:
      PORT: 3000
    depends_on: mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    restart: always
    command: --wiredTigerCacheSizeGB 1.5 # max cache size
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - api-nest-mongo:/data/db

volumes:
  api-nest-mongo:
