# By class lesson

FROM node:17.4.0-alpine
WORKDIR /opt/app
ADD ../../app/package.json package.json
RUN npm install --force
ADD ../../app .

RUN npm run build
RUN npm prune --production
CMD ["node", "./dist/main.js"]
